---
title: "Interactive Graphs with Plotly and Dash"
subtitle: "IDS Workshop on interactive data visualization Plotly and Dash in R"
author: "Giorgio Coppola, Gayatri Shejwal, Lonny Chen"
institute: "Hertie School"
output:
  xaringan::moon_reader:
    css: [default,'simons-touch.css', metropolis, metropolis-fonts] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
      hash: true
---
class: inverse, center, middle
name: welcome

```{css, echo=FALSE} 
@media print { # print out incremental slides; see https://stackoverflow.com/questions/56373198/get-xaringan-incremental-animations-to-print-to-pdf/56374619#56374619
  .has-continuation {
    display: block !important;
  }
}
```

```{r setup, include=FALSE}
# figures formatting setup
options(htmltools.dir.version = FALSE)
library(knitr)
opts_chunk$set(
  prompt = T,
  fig.align="center", #fig.width=6, fig.height=4.5, 
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T, #echo=F, warning=F, message=F
  engine.opts = list(bash = "-l")
  )

## Next hook based on this SO answer: https://stackoverflow.com/a/39025054
knit_hooks$set(
  prompt = function(before, options, envir) {
    options(
      prompt = if (options$engine %in% c('sh','bash')) '$ ' else 'R> ',
      continue = if (options$engine %in% c('sh','bash')) '$ ' else '+ '
      )
})

library(tidyverse)
library(hrbrthemes)
library(fontawesome)
```

# Welcome!
<html><div style='float:left'></div><hr color='#EB811B' size=1px style="width:1000px; margin:auto;"/></html>

---
# Introduction

Data visualization is a powerful mean to understand complex data and communicate insights effectively, revealing the hidden patterns and trends that wouldn't be obvious in tabular data, turning raw data into information.

The tools we are going to introduce today serve exactly this purpose, enhancing the visualization possibilities offered by other static visualization packages such as `ggplot2`. 

<br>
--
**What tools allow to do so?**

Plotly and Dash! And we will introduce both!

Indeed, `plotly` and `dash` are `r emo::ji("dizzy")` interactive `r emo::ji("dizzy")`, in the sense that the user can interact with the data through the graph directly. This allows possibilities for higher understanding of the data. 

---
# Introduction
### Why interactive graphs?  `r emo::ji("metrics")`

--
<br>
* *Engagement*: Makes data come alive (interactive) and is more engaging for users. This increase understanding and retention.

--
* *Depth*: Allows users to drill down and explore nuances, as interaction allows to create narratives more easily. Users can ask 'why' and get answers instantly by exploring the chart or graph.

--
* *Decision-making*: Facilitates more informed decisions.

<br>
Both `plotly` and `dash` are interactive, but we can say that the level of interaction is different: `plotly` appears very similar to a static plot, with the difference that we can hover your cursor over it, accessing further data. `dash` on the other hand, creates proper dashboards, namely HTML apps, allowing even more interaction.

---
# Plotly
### What is Plotly?

--
Plotly is actually a company headquartered in Montreal, Canada, providing online graphing, analytics, and     statistics tools, as well as scientific graphing libraries for Python, R, MATLAB, Perl, Julia, Arduino, JavaScript and REST.
    
  In this contex, with Plotly we refer to the R package for to create interactive graphs.

--
### Advantages of using Plotly

--
- Seamless integration with R and `ggplot2`, through the `ggplotly()` function, that converts your static plots to an interactive web-based version!

--
- Diverse range of plots and customization (wide array of chart types with extensive customization options), as well as the possibility to zoom in and out into the plot, or select a certain part of the plot and explore it specifically.

--
- HTML web integration of graphs, makes visualization more accessible and intuitive. 

---
# Plotly
### Best Practices: Improving Performances



More advanced performance improvements [here](https://plotly-r.com/performance).

---
# Plotly
### Some visualization examples.

A cool, non-trivial, yet not too complex, visualization that encapsulate the power of Plotly:
<br>
Let's track the rise of craft beer production across the US over time with the [Beer Consumption by US State Data](https://github.com/plotly/datasets/blob/master/beers.csv) `r emo::ji("beer")`, for example ???

---
# Plotly
### Example 1: Plotly Bar Plots

A cool, non-trivial, yet not too complex, visualization that encapsulate the power of Plotly:
<br>
Let's track the rise of craft beer production across the US over time with the [Beer Consumption by US State Data](https://github.com/plotly/datasets/blob/master/beers.csv) `r emo::ji("beer")`, for example ???

---
# Dash
### What is Dash?

A web application framework for R (and Python and other programming languages) that allows creating interactive, web-based data dashboards (indeed), turning your interactive plots into full-blown web applications.

--
### Key features

--
- **HTML layout**: 
Design your dashboard layout using simple HTML components, without having to write any actual HTML. Indeed, it structure dashboard components using a set of pre-defined HTML tags within R.

--
- Interactivity through **callbacks**: 
callbacks define interactive behavior by specifying how input changes should modify output components. 
Essentially, when changing a dropdown or move a slider, a callback updates a chart, text, or any other component in real-time. 

--
- **Integration with Plotly** visualizations: Plotly charts can be easily included in Dash, making them part of an    
    interactive dashboard where each component can talk to others.

---
# Dash
### Some visualization examples.

A cool, non-trivial, yet not too complex, visualization that encapsulate the power of Dash:
<br>
Let's create a dash with a map of the public toilet in Berlin using the [Berlin Public Toilet Data](https://www.kaggle.com/datasets/ryanjt/berlin-public-toilets-location/) `r emo::ji("toilet")`, for example ???

---
class: inverse, center, middle, custom-hr
name: thank you

```{css, echo=FALSE} 
.custom-hr hr {
    border-color: #EB811B;
    width: 1000px;
    margin: auto;
    border-width: 1px 0 0 0;
}
```

# Thank you!

<div style="width:1000px; margin:auto;">
    <hr/>
</div>

Now... interactive tutorial!

You find the .Rmd file in the repository. Download it and open it in your R Studio, so that you can follow us directly and complete the exercises we prepared for you directly there!

<br>